# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_remove_book_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='in_print',
            field=models.BooleanField(default=True),
        ),
    ]
